source 'https://github.com/CocoaPods/Specs.git'

target 'pajdeg', :exclusive => true do
  pod "PajdegCore", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PajdegCore", :path => "../"

  pod 'Specta' # , '~> 0.2.1'
  pod 'Expecta'
end
